name: Static checks

on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install npm 11.6.4
        run: npm install -g npm@11.6.4

      - name: Install dependencies
        run: |
          npm ci
          cd example
          npm ci

      - name: setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Check Kotlin formatting
        run: |
          curl -sSL -o ktfmt.jar https://github.com/facebook/ktfmt/releases/download/v0.58/ktfmt-0.58-with-dependencies.jar
          java -jar ktfmt.jar --dry-run --google-style --set-exit-if-changed ./android/src/main/java/expo/modules/liveupdates

      - name: Run Prettier ðŸ’…
        run: npm run format:check

      - name: Run ESLint ðŸ‘®
        run: npm run lint

      - name: Check types ðŸš“
        run: npm run typecheck

      - name: Check types (example app) ðŸš“
        run: npm run typecheck
        working-directory: example
